permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 张幸
  email: angeiv.zhang@gmail.com
  link: http://zhangxing.tk/blog
  weibo: 
  github: http://github.com/angeiv

# 站点信息
title: 张幸的博客 
description: 张幸的博客
url: http://zhangxing.tk/blog
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: https://raw.githubusercontent.com/angeiv/angeiv.github.io/master/gavatar.png
favicon: https://raw.githubusercontent.com/angeiv/angeiv.github.io/master/favicon.ico

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: angeivgithubblog

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
